"""empty message

Revision ID: 412258376dbe
Revises: 
Create Date: 2022-11-18 00:22:20.140641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412258376dbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hospedagem',
    sa.Column('id_hospedagem', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('checkin', sa.Date(), nullable=False),
    sa.Column('checkout', sa.Date(), nullable=False),
    sa.Column('quarto', sa.BigInteger(), nullable=True),
    sa.Column('hospede', sa.String(), nullable=True),
    sa.Column('dias', sa.BigInteger(), nullable=False),
    sa.Column('custo_total', sa.BigInteger(), nullable=True),
    sa.Column('conta_cliente', sa.BigInteger(), nullable=True),
    sa.Column('hospedagem_liquido', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id_hospedagem')
    )
    op.create_table('Hospede',
    sa.Column('id_hospede', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_hospede'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Quarto',
    sa.Column('id_quarto', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('numero', sa.BigInteger(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('preco', sa.BigInteger(), nullable=True),
    sa.Column('custo', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id_quarto')
    )
    op.create_table('Reserva',
    sa.Column('id_reserva', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('checkin', sa.Date(), nullable=False),
    sa.Column('quarto', sa.BigInteger(), nullable=True),
    sa.Column('hospede_cpf', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reserva')
    op.drop_table('Quarto')
    op.drop_table('Hospede')
    op.drop_table('Hospedagem')
    # ### end Alembic commands ###
