"""empty message

Revision ID: 876d133d70bb
Revises: 0cff9ca50b1b
Create Date: 2022-11-16 17:32:33.803492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876d133d70bb'
down_revision = '0cff9ca50b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Quarto', sa.Column('preco', sa.BigInteger(), nullable=True))
    op.add_column('Quarto', sa.Column('custo', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Quarto', 'custo')
    op.drop_column('Quarto', 'preco')
    # ### end Alembic commands ###
