"""empty message

Revision ID: ed90c3314365
Revises: 
Create Date: 2022-11-12 01:25:18.095160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed90c3314365'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hospede',
    sa.Column('id_hospede', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_hospede'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Quarto',
    sa.Column('id_quarto', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('numero', sa.BigInteger(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('custo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_quarto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Quarto')
    op.drop_table('Hospede')
    # ### end Alembic commands ###
